### ISSUE TITLE
Fix: missing icon for card title component

### ISSUE THREAD

**Issue by thaycacac** [comfortdelgro/compass-design#104]
Missing icon for card title component

Actual:
![Screenshot 2022-12-05 at 08 52 18](https://user-images.githubusercontent.com/29374426/205532050-c42e40ed-0b3d-4197-b3b5-4c4e732d49c7.png)

Expect: 
![image](https://user-images.githubusercontent.com/29374426/205532014-dae0cba9-7af3-4014-9037-d21d9b556bfe.png)

**Comment by michael-le-19** [comment]
The button makes use of a **Menu** component which is still being developed. 
![image](https://user-images.githubusercontent.com/117263060/205858536-53a4af87-5cea-478a-b308-099991ae83f4.png)

**Comment by thaycacac** [comment]
If the team complete Menu component, please update card component
