### ISSUE TITLE
Props delegatation

### ISSUE THREAD

**Issue by frencojobs** [comfortdelgro/compass-design#14]
We'll need to decide which props to delegate to the children. This is particularly tricky. For example, we know we'll have to delegate the `className` prop. And it is trivial for component implementations with only one child, for example, the `Button` component. We know for sure that the user would want to pass the `className` prop to the `button` element. But for components such as `Checkbox` where the default `input` element was hidden and a custom design was implemented via `label` element, this is a hard question to answer. Should we pass the `className` prop to the `input` or to `label`? What would be ideal and - most importantly - intuitive for the user?

We'll also have to think about native HTML props such as `onClick` and `disabled`. They are implemented with different names in `react-aria` such as `onPress` and `isDisabled`. Currently we only accept props in the format of `react-aria`, i.e. the user must use `onPress` instead of `onClick` and `isDisabled` instead of `disabled` etc. Whether we should remap those native props to aria props is to be discussed.

Another point of discussion would be about `style` attribute. Currently we allow the user to modify the components using the `css` prop. Our advice for the user would be to use the `css` prop because then the user can get all the goodness provided by stitches. Therefore, using the `style` attribute should be an anti-pattern. Whether we should allow `style` attribute is also to be discussed.

**Comment by TaiCBui** [comment]
1. I think we should fully comply with the conventions of react aria, 'cause they follow https://www.w3.org/WAI/ARIA/apg/, which is a good standard to follow.
2. We should keep css props, no need to use style. css is much more powerfull than style.
3. I think we should always pass className prop to the parent element. for example, regarding the checkbox element, we pass the className props to its container, not label nor input element. If the user wants to access the child elements, they can go from the parent component





[3:55](https://fpt-cdg.slack.com/archives/D04AP4V4GQZ/p1668761748485809)
and you're sure you want o allow className delegation though? 'cause I only see this on base components
