### ISSUE TITLE
Fix: Table missing border

### ISSUE THREAD

**Issue by michael-le-19** [comfortdelgro/compass-design#232]
Design:
![image](https://user-images.githubusercontent.com/117263060/210697796-edcc5d54-dca8-4966-bed9-69cd3a88a1fa.png)

Actual:
![image](https://user-images.githubusercontent.com/117263060/210697849-38975b2d-3f50-4762-a0d2-48a664eee94a.png)

**Comment by yagin94** [comment]
Fixed
