### ISSUE TITLE
Add dropdown with the flag for each item

### ISSUE THREAD

**Issue by thaycacac** [comfortdelgro/compass-design#373]
I want to drop down can
- Show flag for each item
- User can search to find country

Design:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/29374426/219533133-55f8ac21-5463-48ed-bc5d-17545cb21313.png">

https://www.figma.com/file/JSiK3cmMmxTt8qhR3dty8t/Workbench-Design-System?node-id=6565%3A105044&t=FqZqMsrgp1MzTuVc-0

**Comment by TungNT107** [comment]
This feature will be release on new version, inside Dropdown.Flag
