### ISSUE TITLE
Fix: Tooltip for TEM is cut off at the side

### ISSUE THREAD

**Issue by hoangnx30** [comfortdelgro/compass-design#479]
- Tooltip for TEM is cut off at the side
- Tooltip still appears when scrolling

<img width="428" alt="image" src="https://user-images.githubusercontent.com/43129138/222056824-3592743a-dcb5-4361-8e23-27cd3f9b47ba.png">

**Comment by Tai-Chi-Bui** [comment]
https://ant.design/components/tooltip
