### ISSUE TITLE
Fix: component imports in stories.tsx files. At least 8 components import wrong.

### ISSUE THREAD

**Issue by Tai-Chi-Bui** [comfortdelgro/compass-design#69]

**Comment by frencojobs** [comment]
There's a bug on ladle that's preventing imports of re-exported members. For example, if you want to use the button component, you must import from `button/button` and not from `button` which would point to `button/index.ts` and then ladle will fail.

**Comment by Tai-Chi-Bui** [comment]
> 

I think import from './index' just be fine.
