### ISSUE TITLE
[Multiple-dropdown] Prop "description" didnt work

### ISSUE THREAD

**Issue by fpt-tom-du** [comfortdelgro/compass-design#740]
<img width="1485" alt="image" src="https://github.com/comfortdelgro/compass-design/assets/125246230/f24f5143-cb99-4dcb-bc23-c2bb8d040115">

**Comment by TungNT107** [comment]
<img width="500" alt="Screenshot 2023-05-30 at 13 38 39" src="https://github.com/comfortdelgro/compass-design/assets/117718974/c4239a53-2b65-45ef-8727-e1a0a63675ce">
- This description is only for element props
