### ISSUE TITLE
Issues with dropdowns when integrating react-hook-form

### ISSUE THREAD

**Issue by pieliedie** [comfortdelgro/compass-design#743]
![image](https://github.com/comfortdelgro/compass-design/assets/7071853/87cb09d0-04a1-48e5-8d6a-ed0106779133)

From top down, I have Dropdown.Select, Dropdown.Flag, Dropdown.Combobox and MultipleDropdown. There are no initial values. On the first render, the Select and Combobox trigger error state while the others don't.  Here is the [link](https://github.com/comfortdelgro/compass-design/blob/feature/create-example-dropdowns-using-react-hook-form/apps/docs/src/components/DropdownsForm.tsx) to my sample, pls take a look.

**Comment by TungNT107** [comment]
<img width="737" alt="Screenshot 2023-05-30 at 14 42 52" src="https://github.com/comfortdelgro/compass-design/assets/117718974/70e9274b-1e9f-49e6-9b5a-6e843f26e74e">
Already fixed in next.10
