### ISSUE TITLE
[Dropdown.Flag] Nothing selected when set flagKeyType='country-code'

### ISSUE THREAD

**Issue by pieliedie** [comfortdelgro/compass-design#751]
OS: Windows 10, MS Edge Chromium.

Set flagKeyType='country-code' to the Dropdown.Flag. Select one country.

Expected: The country is chosen and displayed on the dropdown.
Actual: Nothing selected.

By the way, 'phone-code' is not available anymore.

**Comment by TungNT107** [comment]
<img width="842" alt="image" src="https://github.com/comfortdelgro/compass-design/assets/117718974/7de8b67d-6b9c-4cd0-9da6-fcfdc80d0b8d">
Using incorrect props on docs and ladle
