### ISSUE TITLE
Fix: Missing props type for badge component

### ISSUE THREAD

**Issue by thaycacac** [comfortdelgro/compass-design#97]
I think need more props for types like for chart, for tag

![Screenshot 2022-12-02 at 14 59 46](https://user-images.githubusercontent.com/29374426/205244369-7baaeccc-03b9-4c34-ba18-aeb047351797.png)

**Comment by frencojobs** [comment]
We have these variants, they're called `secondary`(instead of `chart`) and `outline`(instead of `tag`) and me and Harsai have verbally agreed to go with that. It's just that the figma wasn't updated. It will be updated shortly.

**Comment by thaycacac** [comment]
I got it. thanks
